AWSTemplateFormatVersion: 2010-09-09
Description: Main Stack for POC

Parameters:

  EnvironmentType: 
      Description: The environment type
      Type: String
      Default: dev
      AllowedValues: 
        - dev
        - qa
        - prod

  VPC:
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 192.168.0.0/16
    Description: CIDR Block for the VPC
    
  PublicSubnet1CIDR:
    Type: String
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x 
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 192.168.1.0/16
    Description: CIDR Block for the public subnet 1
  
  PublicSubnet2CIDR:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x 
    Default: 192.168.2.0/16
    Description: CIDR Block for the public subnet 2
  
  PrivateSubnet1CIDR:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x
    Default: 192.168.4.0/16
    Description: CIDR block for private subnet 1 
    
  
  PrivateSubnet2CIDR:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Must be a valid IP range in x.x.x.x/x
    Default: 192.168.5.0/16
    Description: CIDR block for private subnet 2

  ALBAccessCIDR:
    Description: ALB access CIDR
    Type: String
    Default: 0.0.0.0/0
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
  
  
  ServerInstanceType:
    ConstraintDescription: Select instance type.
    Default: t2.micro
    Description: instance type
    Type: String
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
      
  RemoteAccessCIDR:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: Allowed CIDR block for external SSH access
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
  
  KeyPairName: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be a valid Key Pair

Resources:
  RACVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://templates-2wdedgf.s3.ap-south-1.amazonaws.com/VPC.yaml
      Parameters:
        VPC: !Ref VPC 
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR 
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
  HelloWorldStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://templates-2wdedgf.s3.ap-south-1.amazonaws.com/ALBEC2.yaml
      Parameters:
        ALBAccessCIDR: !Ref ALBAccessCIDR
        ServerInstanceType: !Ref ServerInstanceType
        EnvironmentType: !Ref EnvironmentType
        KeyPairName: !Ref KeyPairName
        VPCID: !GetAtt RACVPCStack.Outputs.RACVPCID
        PublicSubnet1: !GetAtt RACVPCStack.Outputs.RACPublicSubnet1
        PublicSubnet2: !GetAtt RACVPCStack.Outputs.RACPublicSubnet2
        PrivateSubnet1: !GetAtt RACVPCStack.Outputs.RACPrivateSubnet1
        PrivateSubnet2: !GetAtt RACVPCStack.Outputs.RACPrivateSubnet2
  
        
        
  
  
        
    
        

  

    
  

    

    
    